/// A representation of a country with its metadata.
library;

class Country {
  final String name;
  final String nativeName;
  final String countryCode; // ISO Alpha-2
  final String isoNumeric;
  final String flag;
  final String currency;
  final String currencySymbol;
  final String phoneCode;
  final String capitalCity;

  const Country({
    this.name = '',
    this.nativeName = '',
    this.countryCode = '',
    this.isoNumeric = '',
    this.flag = '',
    this.currency = '',
    this.currencySymbol = '',
    this.phoneCode = '',
    this.capitalCity = '',
  });

  factory Country.fromMap(Map<String, dynamic> map) {
    return Country(
      name: map['name'] ?? '',
      nativeName: map['nativeName'] ?? '',
      countryCode: map['countryCode'] ?? '',
      isoNumeric: map['isoNumeric'] ?? '',
      flag: map['flag'] ?? '',
      currency: map['currency'] ?? '',
      currencySymbol: map['currencySymbol'] ?? '',
      phoneCode: map['phoneCode'] ?? '',
      capitalCity: map['capitalCity'] ?? '',
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'nativeName': nativeName,
      'countryCode': countryCode,
      'isoNumeric': isoNumeric,
      'flag': flag,
      'currency': currency,
      'currencySymbol': currencySymbol,
      'phoneCode': phoneCode,
      'capitalCity': capitalCity,
    };
  }

  // --------------------------------------------------------------------------
  // Utility Methods
  // --------------------------------------------------------------------------

  /// Finds a country by its ISO Alpha-2 code (case-insensitive).
  static Country? fromCode(String code) {
    try {
      return all.firstWhere(
        (c) => c.countryCode.toUpperCase() == code.toUpperCase(),
      );
    } catch (_) {
      return null;
    }
  }

  /// Finds a country by its emoji flag.
  static Country? fromFlag(String flag) {
    try {
      return all.firstWhere((c) => c.flag == flag);
    } catch (_) {
      return null;
    }
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Country &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          countryCode == other.countryCode;

  @override
  int get hashCode => name.hashCode ^ countryCode.hashCode;

  // --------------------------------------------------------------------------
  // Static Country Instances (camelCase)
  // --------------------------------------------------------------------------

  static const Country worldWide = Country(
    name: "World Wide",
    countryCode: "",
    flag: "🌎",
  );

  static const afghanistan = Country(
    name: "Afghanistan",
    nativeName: "افغانستان",
    countryCode: "AF",
    isoNumeric: "004",
    flag: "🇦🇫",
    currency: "AFN",
    currencySymbol: "؋",
    phoneCode: "+93",
    capitalCity: "Kabul",
  );
  static const albania = Country(
    name: "Albania",
    nativeName: "Shqipëria",
    countryCode: "AL",
    isoNumeric: "008",
    flag: "🇦🇱",
    currency: "ALL",
    currencySymbol: "L",
    phoneCode: "+355",
    capitalCity: "Tirana",
  );
  static const algeria = Country(
    name: "Algeria",
    nativeName: "الجزائر",
    countryCode: "DZ",
    isoNumeric: "012",
    flag: "🇩🇿",
    currency: "DZD",
    currencySymbol: "د.ج",
    phoneCode: "+213",
    capitalCity: "Algiers",
  );
  static const andorra = Country(
    name: "Andorra",
    nativeName: "Andorra",
    countryCode: "AD",
    isoNumeric: "020",
    flag: "🇦🇩",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+376",
    capitalCity: "Andorra la Vella",
  );
  static const angola = Country(
    name: "Angola",
    nativeName: "Angola",
    countryCode: "AO",
    isoNumeric: "024",
    flag: "🇦🇴",
    currency: "AOA",
    currencySymbol: "Kz",
    phoneCode: "+244",
    capitalCity: "Luanda",
  );
  static const antiguaAndBarbuda = Country(
    name: "Antigua and Barbuda",
    nativeName: "Antigua and Barbuda",
    countryCode: "AG",
    isoNumeric: "028",
    flag: "🇦🇬",
    currency: "XCD",
    currencySymbol: r"$",
    phoneCode: "+1-268",
    capitalCity: "St. John's",
  );
  static const argentina = Country(
    name: "Argentina",
    nativeName: "Argentina",
    countryCode: "AR",
    isoNumeric: "032",
    flag: "🇦🇷",
    currency: "ARS",
    currencySymbol: r"$",
    phoneCode: "+54",
    capitalCity: "Buenos Aires",
  );
  static const armenia = Country(
    name: "Armenia",
    nativeName: "Հայաստան",
    countryCode: "AM",
    isoNumeric: "051",
    flag: "🇦🇲",
    currency: "AMD",
    currencySymbol: "֏",
    phoneCode: "+374",
    capitalCity: "Yerevan",
  );
  static const australia = Country(
    name: "Australia",
    nativeName: "Australia",
    countryCode: "AU",
    isoNumeric: "036",
    flag: "🇦🇺",
    currency: "AUD",
    currencySymbol: r"$",
    phoneCode: "+61",
    capitalCity: "Canberra",
  );
  static const austria = Country(
    name: "Austria",
    nativeName: "Österreich",
    countryCode: "AT",
    isoNumeric: "040",
    flag: "🇦🇹",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+43",
    capitalCity: "Vienna",
  );
  static const azerbaijan = Country(
    name: "Azerbaijan",
    nativeName: "Azərbaycan",
    countryCode: "AZ",
    isoNumeric: "031",
    flag: "🇦🇿",
    currency: "AZN",
    currencySymbol: "₼",
    phoneCode: "+994",
    capitalCity: "Baku",
  );
  static const bahamas = Country(
    name: "Bahamas",
    nativeName: "Bahamas",
    countryCode: "BS",
    isoNumeric: "044",
    flag: "🇧🇸",
    currency: "BSD",
    currencySymbol: r"$",
    phoneCode: "+1-242",
    capitalCity: "Nassau",
  );
  static const bahrain = Country(
    name: "Bahrain",
    nativeName: "البحرين",
    countryCode: "BH",
    isoNumeric: "048",
    flag: "🇧🇭",
    currency: "BHD",
    currencySymbol: ".د.ب",
    phoneCode: "+973",
    capitalCity: "Manama",
  );
  static const bangladesh = Country(
    name: "Bangladesh",
    nativeName: "বাংলাদেশ",
    countryCode: "BD",
    isoNumeric: "050",
    flag: "🇧🇩",
    currency: "BDT",
    currencySymbol: "৳",
    phoneCode: "+880",
    capitalCity: "Dhaka",
  );
  static const barbados = Country(
    name: "Barbados",
    nativeName: "Barbados",
    countryCode: "BB",
    isoNumeric: "052",
    flag: "🇧🇧",
    currency: "BBD",
    currencySymbol: r"$",
    phoneCode: "+1-246",
    capitalCity: "Bridgetown",
  );
  static const belarus = Country(
    name: "Belarus",
    nativeName: "Беларусь",
    countryCode: "BY",
    isoNumeric: "112",
    flag: "🇧🇾",
    currency: "BYN",
    currencySymbol: "Br",
    phoneCode: "+375",
    capitalCity: "Minsk",
  );
  static const belgium = Country(
    name: "Belgium",
    nativeName: "België",
    countryCode: "BE",
    isoNumeric: "056",
    flag: "🇧🇪",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+32",
    capitalCity: "Brussels",
  );
  static const belize = Country(
    name: "Belize",
    nativeName: "Belize",
    countryCode: "BZ",
    isoNumeric: "084",
    flag: "🇧🇿",
    currency: "BZD",
    currencySymbol: r"$",
    phoneCode: "+501",
    capitalCity: "Belmopan",
  );
  static const benin = Country(
    name: "Benin",
    nativeName: "Bénin",
    countryCode: "BJ",
    isoNumeric: "204",
    flag: "🇧🇯",
    currency: "XOF",
    currencySymbol: "Fr",
    phoneCode: "+229",
    capitalCity: "Porto-Novo",
  );
  static const bhutan = Country(
    name: "Bhutan",
    nativeName: "འབྲུག་ཡུལ་",
    countryCode: "BT",
    isoNumeric: "064",
    flag: "🇧🇹",
    currency: "BTN",
    currencySymbol: "Nu.",
    phoneCode: "+975",
    capitalCity: "Thimphu",
  );
  static const bolivia = Country(
    name: "Bolivia",
    nativeName: "Bolivia",
    countryCode: "BO",
    isoNumeric: "068",
    flag: "🇧🇴",
    currency: "BOB",
    currencySymbol: "Bs.",
    phoneCode: "+591",
    capitalCity: "Sucre",
  );
  static const bosniaAndHerzegovina = Country(
    name: "Bosnia and Herzegovina",
    nativeName: "Bosna i Hercegovina",
    countryCode: "BA",
    isoNumeric: "070",
    flag: "🇧🇦",
    currency: "BAM",
    currencySymbol: "KM",
    phoneCode: "+387",
    capitalCity: "Sarajevo",
  );
  static const botswana = Country(
    name: "Botswana",
    nativeName: "Botswana",
    countryCode: "BW",
    isoNumeric: "072",
    flag: "🇧🇼",
    currency: "BWP",
    currencySymbol: "P",
    phoneCode: "+267",
    capitalCity: "Gaborone",
  );
  static const brazil = Country(
    name: "Brazil",
    nativeName: "Brasil",
    countryCode: "BR",
    isoNumeric: "076",
    flag: "🇧🇷",
    currency: "BRL",
    currencySymbol: r"R$",
    phoneCode: "+55",
    capitalCity: "Brasília",
  );
  static const brunei = Country(
    name: "Brunei",
    nativeName: "Brunei",
    countryCode: "BN",
    isoNumeric: "096",
    flag: "🇧🇳",
    currency: "BND",
    currencySymbol: r"$",
    phoneCode: "+673",
    capitalCity: "Bandar Seri Begawan",
  );
  static const bulgaria = Country(
    name: "Bulgaria",
    nativeName: "България",
    countryCode: "BG",
    isoNumeric: "100",
    flag: "🇧🇬",
    currency: "BGN",
    currencySymbol: "лв",
    phoneCode: "+359",
    capitalCity: "Sofia",
  );
  static const burkinaFaso = Country(
    name: "Burkina Faso",
    nativeName: "Burkina Faso",
    countryCode: "BF",
    isoNumeric: "854",
    flag: "🇧🇫",
    currency: "XOF",
    currencySymbol: "Fr",
    phoneCode: "+226",
    capitalCity: "Ouagadougou",
  );
  static const burundi = Country(
    name: "Burundi",
    nativeName: "Burundi",
    countryCode: "BI",
    isoNumeric: "108",
    flag: "🇧🇮",
    currency: "BIF",
    currencySymbol: "Fr",
    phoneCode: "+257",
    capitalCity: "Gitega",
  );
  static const cambodia = Country(
    name: "Cambodia",
    nativeName: "កម្ពុជា",
    countryCode: "KH",
    isoNumeric: "116",
    flag: "🇰🇭",
    currency: "KHR",
    currencySymbol: "៛",
    phoneCode: "+855",
    capitalCity: "Phnom Penh",
  );
  static const cameroon = Country(
    name: "Cameroon",
    nativeName: "Cameroun",
    countryCode: "CM",
    isoNumeric: "120",
    flag: "🇨🇲",
    currency: "XAF",
    currencySymbol: "Fr",
    phoneCode: "+237",
    capitalCity: "Yaoundé",
  );
  static const canada = Country(
    name: "Canada",
    nativeName: "Canada",
    countryCode: "CA",
    isoNumeric: "124",
    flag: "🇨🇦",
    currency: "CAD",
    currencySymbol: r"$",
    phoneCode: "+1",
    capitalCity: "Ottawa",
  );
  static const capeVerde = Country(
    name: "Cape Verde",
    nativeName: "Cabo Verde",
    countryCode: "CV",
    isoNumeric: "132",
    flag: "🇨🇻",
    currency: "CVE",
    currencySymbol: "Esc",
    phoneCode: "+238",
    capitalCity: "Praia",
  );
  static const centralAfricanRepublic = Country(
    name: "Central African Republic",
    nativeName: "République centrafricaine",
    countryCode: "CF",
    isoNumeric: "140",
    flag: "🇨🇫",
    currency: "XAF",
    currencySymbol: "Fr",
    phoneCode: "+236",
    capitalCity: "Bangui",
  );
  static const chad = Country(
    name: "Chad",
    nativeName: "Tchad",
    countryCode: "TD",
    isoNumeric: "148",
    flag: "🇹🇩",
    currency: "XAF",
    currencySymbol: "Fr",
    phoneCode: "+235",
    capitalCity: "N'Djamena",
  );
  static const chile = Country(
    name: "Chile",
    nativeName: "Chile",
    countryCode: "CL",
    isoNumeric: "152",
    flag: "🇨🇱",
    currency: "CLP",
    currencySymbol: r"$",
    phoneCode: "+56",
    capitalCity: "Santiago",
  );
  static const china = Country(
    name: "China",
    nativeName: "中国",
    countryCode: "CN",
    isoNumeric: "156",
    flag: "🇨🇳",
    currency: "CNY",
    currencySymbol: "¥",
    phoneCode: "+86",
    capitalCity: "Beijing",
  );
  static const colombia = Country(
    name: "Colombia",
    nativeName: "Colombia",
    countryCode: "CO",
    isoNumeric: "170",
    flag: "🇨🇴",
    currency: "COP",
    currencySymbol: r"$",
    phoneCode: "+57",
    capitalCity: "Bogotá",
  );
  static const comoros = Country(
    name: "Comoros",
    nativeName: "Comores",
    countryCode: "KM",
    isoNumeric: "174",
    flag: "🇰🇲",
    currency: "KMF",
    currencySymbol: "Fr",
    phoneCode: "+269",
    capitalCity: "Moroni",
  );
  static const congo = Country(
    name: "Congo",
    nativeName: "République du Congo",
    countryCode: "CG",
    isoNumeric: "178",
    flag: "🇨🇬",
    currency: "XAF",
    currencySymbol: "Fr",
    phoneCode: "+242",
    capitalCity: "Brazzaville",
  );
  static const costaRica = Country(
    name: "Costa Rica",
    nativeName: "Costa Rica",
    countryCode: "CR",
    isoNumeric: "188",
    flag: "🇨🇷",
    currency: "CRC",
    currencySymbol: "₡",
    phoneCode: "+506",
    capitalCity: "San José",
  );
  static const croatia = Country(
    name: "Croatia",
    nativeName: "Hrvatska",
    countryCode: "HR",
    isoNumeric: "191",
    flag: "🇭🇷",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+385",
    capitalCity: "Zagreb",
  );
  static const cuba = Country(
    name: "Cuba",
    nativeName: "Cuba",
    countryCode: "CU",
    isoNumeric: "192",
    flag: "🇨🇺",
    currency: "CUP",
    currencySymbol: r"$",
    phoneCode: "+53",
    capitalCity: "Havana",
  );
  static const cyprus = Country(
    name: "Cyprus",
    nativeName: "Κύπρος",
    countryCode: "CY",
    isoNumeric: "196",
    flag: "🇨🇾",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+357",
    capitalCity: "Nicosia",
  );
  static const czechRepublic = Country(
    name: "Czech Republic",
    nativeName: "Česko",
    countryCode: "CZ",
    isoNumeric: "203",
    flag: "🇨🇿",
    currency: "CZK",
    currencySymbol: "Kč",
    phoneCode: "+420",
    capitalCity: "Prague",
  );
  static const denmark = Country(
    name: "Denmark",
    nativeName: "Danmark",
    countryCode: "DK",
    isoNumeric: "208",
    flag: "🇩🇰",
    currency: "DKK",
    currencySymbol: "kr",
    phoneCode: "+45",
    capitalCity: "Copenhagen",
  );
  static const djibouti = Country(
    name: "Djibouti",
    nativeName: "Djibouti",
    countryCode: "DJ",
    isoNumeric: "262",
    flag: "🇩🇯",
    currency: "DJF",
    currencySymbol: "Fr",
    phoneCode: "+253",
    capitalCity: "Djibouti",
  );
  static const dominica = Country(
    name: "Dominica",
    nativeName: "Dominica",
    countryCode: "DM",
    isoNumeric: "212",
    flag: "🇩🇲",
    currency: "XCD",
    currencySymbol: r"$",
    phoneCode: "+1-767",
    capitalCity: "Roseau",
  );
  static const dominicanRepublic = Country(
    name: "Dominican Republic",
    nativeName: "República Dominicana",
    countryCode: "DO",
    isoNumeric: "214",
    flag: "🇩🇴",
    currency: "DOP",
    currencySymbol: r"$",
    phoneCode: "+1-809",
    capitalCity: "Santo Domingo",
  );
  static const ecuador = Country(
    name: "Ecuador",
    nativeName: "Ecuador",
    countryCode: "EC",
    isoNumeric: "218",
    flag: "🇪🇨",
    currency: "USD",
    currencySymbol: r"$",
    phoneCode: "+593",
    capitalCity: "Quito",
  );
  static const egypt = Country(
    name: "Egypt",
    nativeName: "مصر",
    countryCode: "EG",
    isoNumeric: "818",
    flag: "🇪🇬",
    currency: "EGP",
    currencySymbol: "£",
    phoneCode: "+20",
    capitalCity: "Cairo",
  );
  static const elSalvador = Country(
    name: "El Salvador",
    nativeName: "El Salvador",
    countryCode: "SV",
    isoNumeric: "222",
    flag: "🇸🇻",
    currency: "USD",
    currencySymbol: r"$",
    phoneCode: "+503",
    capitalCity: "San Salvador",
  );
  static const equatorialGuinea = Country(
    name: "Equatorial Guinea",
    nativeName: "Guinea Ecuatorial",
    countryCode: "GQ",
    isoNumeric: "226",
    flag: "🇬🇶",
    currency: "XAF",
    currencySymbol: "Fr",
    phoneCode: "+240",
    capitalCity: "Malabo",
  );
  static const eritrea = Country(
    name: "Eritrea",
    nativeName: "ኤርትራ",
    countryCode: "ER",
    isoNumeric: "232",
    flag: "🇪🇷",
    currency: "ERN",
    currencySymbol: "Nfk",
    phoneCode: "+291",
    capitalCity: "Asmara",
  );
  static const estonia = Country(
    name: "Estonia",
    nativeName: "Eesti",
    countryCode: "EE",
    isoNumeric: "233",
    flag: "🇪🇪",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+372",
    capitalCity: "Tallinn",
  );
  static const eswatini = Country(
    name: "Eswatini",
    nativeName: "eSwatini",
    countryCode: "SZ",
    isoNumeric: "748",
    flag: "🇸🇿",
    currency: "SZL",
    currencySymbol: "L",
    phoneCode: "+268",
    capitalCity: "Mbabane",
  );
  static const ethiopia = Country(
    name: "Ethiopia",
    nativeName: "ኢትዮጵያ",
    countryCode: "ET",
    isoNumeric: "231",
    flag: "🇪🇹",
    currency: "ETB",
    currencySymbol: "Br",
    phoneCode: "+251",
    capitalCity: "Addis Ababa",
  );
  static const fiji = Country(
    name: "Fiji",
    nativeName: "Fiji",
    countryCode: "FJ",
    isoNumeric: "242",
    flag: "🇫🇯",
    currency: "FJD",
    currencySymbol: r"$",
    phoneCode: "+679",
    capitalCity: "Suva",
  );
  static const finland = Country(
    name: "Finland",
    nativeName: "Suomi",
    countryCode: "FI",
    isoNumeric: "246",
    flag: "🇫🇮",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+358",
    capitalCity: "Helsinki",
  );
  static const france = Country(
    name: "France",
    nativeName: "France",
    countryCode: "FR",
    isoNumeric: "250",
    flag: "🇫🇷",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+33",
    capitalCity: "Paris",
  );
  static const gabon = Country(
    name: "Gabon",
    nativeName: "Gabon",
    countryCode: "GA",
    isoNumeric: "266",
    flag: "🇬🇦",
    currency: "XAF",
    currencySymbol: "Fr",
    phoneCode: "+241",
    capitalCity: "Libreville",
  );
  static const gambia = Country(
    name: "Gambia",
    nativeName: "Gambia",
    countryCode: "GM",
    isoNumeric: "270",
    flag: "🇬🇲",
    currency: "GMD",
    currencySymbol: "D",
    phoneCode: "+220",
    capitalCity: "Banjul",
  );
  static const georgia = Country(
    name: "Georgia",
    nativeName: "საქართველო",
    countryCode: "GE",
    isoNumeric: "268",
    flag: "🇬🇪",
    currency: "GEL",
    currencySymbol: "₾",
    phoneCode: "+995",
    capitalCity: "Tbilisi",
  );
  static const germany = Country(
    name: "Germany",
    nativeName: "Deutschland",
    countryCode: "DE",
    isoNumeric: "276",
    flag: "🇩🇪",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+49",
    capitalCity: "Berlin",
  );
  static const ghana = Country(
    name: "Ghana",
    nativeName: "Ghana",
    countryCode: "GH",
    isoNumeric: "288",
    flag: "🇬🇭",
    currency: "GHS",
    currencySymbol: "₵",
    phoneCode: "+233",
    capitalCity: "Accra",
  );
  static const greece = Country(
    name: "Greece",
    nativeName: "Ελλάδα",
    countryCode: "GR",
    isoNumeric: "300",
    flag: "🇬🇷",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+30",
    capitalCity: "Athens",
  );
  static const grenada = Country(
    name: "Grenada",
    nativeName: "Grenada",
    countryCode: "GD",
    isoNumeric: "308",
    flag: "🇬🇩",
    currency: "XCD",
    currencySymbol: r"$",
    phoneCode: "+1-473",
    capitalCity: "St. George's",
  );
  static const guatemala = Country(
    name: "Guatemala",
    nativeName: "Guatemala",
    countryCode: "GT",
    isoNumeric: "320",
    flag: "🇬🇹",
    currency: "GTQ",
    currencySymbol: "Q",
    phoneCode: "+502",
    capitalCity: "Guatemala City",
  );
  static const guinea = Country(
    name: "Guinea",
    nativeName: "Guinée",
    countryCode: "GN",
    isoNumeric: "324",
    flag: "🇬🇳",
    currency: "GNF",
    currencySymbol: "Fr",
    phoneCode: "+224",
    capitalCity: "Conakry",
  );
  static const guineaBissau = Country(
    name: "Guinea-Bissau",
    nativeName: "Guiné-Bissau",
    countryCode: "GW",
    isoNumeric: "624",
    flag: "🇬🇼",
    currency: "XOF",
    currencySymbol: "Fr",
    phoneCode: "+245",
    capitalCity: "Bissau",
  );
  static const guyana = Country(
    name: "Guyana",
    nativeName: "Guyana",
    countryCode: "GY",
    isoNumeric: "328",
    flag: "🇬🇾",
    currency: "GYD",
    currencySymbol: r"$",
    phoneCode: "+592",
    capitalCity: "Georgetown",
  );
  static const haiti = Country(
    name: "Haiti",
    nativeName: "Haïti",
    countryCode: "HT",
    isoNumeric: "332",
    flag: "🇭🇹",
    currency: "HTG",
    currencySymbol: "G",
    phoneCode: "+509",
    capitalCity: "Port-au-Prince",
  );
  static const honduras = Country(
    name: "Honduras",
    nativeName: "Honduras",
    countryCode: "HN",
    isoNumeric: "340",
    flag: "🇭🇳",
    currency: "HNL",
    currencySymbol: "L",
    phoneCode: "+504",
    capitalCity: "Tegucigalpa",
  );
  static const hungary = Country(
    name: "Hungary",
    nativeName: "Magyarország",
    countryCode: "HU",
    isoNumeric: "348",
    flag: "🇭🇺",
    currency: "HUF",
    currencySymbol: "Ft",
    phoneCode: "+36",
    capitalCity: "Budapest",
  );
  static const iceland = Country(
    name: "Iceland",
    nativeName: "Ísland",
    countryCode: "IS",
    isoNumeric: "352",
    flag: "🇮🇸",
    currency: "ISK",
    currencySymbol: "kr",
    phoneCode: "+354",
    capitalCity: "Reykjavík",
  );
  static const india = Country(
    name: "India",
    nativeName: "भारत",
    countryCode: "IN",
    isoNumeric: "356",
    flag: "🇮🇳",
    currency: "INR",
    currencySymbol: "₹",
    phoneCode: "+91",
    capitalCity: "New Delhi",
  );
  static const indonesia = Country(
    name: "Indonesia",
    nativeName: "Indonesia",
    countryCode: "ID",
    isoNumeric: "360",
    flag: "🇮🇩",
    currency: "IDR",
    currencySymbol: "Rp",
    phoneCode: "+62",
    capitalCity: "Jakarta",
  );
  static const iran = Country(
    name: "Iran",
    nativeName: "ایران",
    countryCode: "IR",
    isoNumeric: "364",
    flag: "🇮🇷",
    currency: "IRR",
    currencySymbol: "﷼",
    phoneCode: "+98",
    capitalCity: "Tehran",
  );
  static const iraq = Country(
    name: "Iraq",
    nativeName: "العراق",
    countryCode: "IQ",
    isoNumeric: "368",
    flag: "🇮🇶",
    currency: "IQD",
    currencySymbol: "ع.د",
    phoneCode: "+964",
    capitalCity: "Baghdad",
  );
  static const ireland = Country(
    name: "Ireland",
    nativeName: "Éire",
    countryCode: "IE",
    isoNumeric: "372",
    flag: "🇮🇪",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+353",
    capitalCity: "Dublin",
  );
  static const israel = Country(
    name: "Israel",
    nativeName: "יִשְׂרָאֵל",
    countryCode: "IL",
    isoNumeric: "376",
    flag: "🇮🇱",
    currency: "ILS",
    currencySymbol: "₪",
    phoneCode: "+972",
    capitalCity: "Jerusalem",
  );
  static const italy = Country(
    name: "Italy",
    nativeName: "Italia",
    countryCode: "IT",
    isoNumeric: "380",
    flag: "🇮🇹",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+39",
    capitalCity: "Rome",
  );
  static const jamaica = Country(
    name: "Jamaica",
    nativeName: "Jamaica",
    countryCode: "JM",
    isoNumeric: "388",
    flag: "🇯🇲",
    currency: "JMD",
    currencySymbol: r"$",
    phoneCode: "+1-876",
    capitalCity: "Kingston",
  );
  static const japan = Country(
    name: "Japan",
    nativeName: "日本",
    countryCode: "JP",
    isoNumeric: "392",
    flag: "🇯🇵",
    currency: "JPY",
    currencySymbol: "¥",
    phoneCode: "+81",
    capitalCity: "Tokyo",
  );
  static const jordan = Country(
    name: "Jordan",
    nativeName: "الأردن",
    countryCode: "JO",
    isoNumeric: "400",
    flag: "🇯🇴",
    currency: "JOD",
    currencySymbol: "د.ا",
    phoneCode: "+962",
    capitalCity: "Amman",
  );
  static const kazakhstan = Country(
    name: "Kazakhstan",
    nativeName: "Қазақستان",
    countryCode: "KZ",
    isoNumeric: "398",
    flag: "🇰🇿",
    currency: "KZT",
    currencySymbol: "₸",
    phoneCode: "+7",
    capitalCity: "Astana",
  );
  static const kenya = Country(
    name: "Kenya",
    nativeName: "Kenya",
    countryCode: "KE",
    isoNumeric: "404",
    flag: "🇰🇪",
    currency: "KES",
    currencySymbol: "Sh",
    phoneCode: "+254",
    capitalCity: "Nairobi",
  );
  static const kiribati = Country(
    name: "Kiribati",
    nativeName: "Kiribati",
    countryCode: "KI",
    isoNumeric: "296",
    flag: "🇰🇮",
    currency: "AUD",
    currencySymbol: r"$",
    phoneCode: "+686",
    capitalCity: "Tarawa",
  );
  static const kuwait = Country(
    name: "Kuwait",
    nativeName: "الكويت",
    countryCode: "KW",
    isoNumeric: "414",
    flag: "🇰🇼",
    currency: "KWD",
    currencySymbol: "د.ك",
    phoneCode: "+965",
    capitalCity: "Kuwait City",
  );
  static const kyrgyzstan = Country(
    name: "Kyrgyzstan",
    nativeName: "Кыргызстан",
    countryCode: "KG",
    isoNumeric: "417",
    flag: "🇰🇬",
    currency: "KGS",
    currencySymbol: "с",
    phoneCode: "+996",
    capitalCity: "Bishkek",
  );
  static const laos = Country(
    name: "Laos",
    nativeName: "ສປປ ລາວ",
    countryCode: "LA",
    isoNumeric: "418",
    flag: "🇱🇦",
    currency: "LAK",
    currencySymbol: "₭",
    phoneCode: "+856",
    capitalCity: "Vientiane",
  );
  static const latvia = Country(
    name: "Latvia",
    nativeName: "Latvija",
    countryCode: "LV",
    isoNumeric: "428",
    flag: "🇱🇻",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+371",
    capitalCity: "Riga",
  );
  static const lebanon = Country(
    name: "Lebanon",
    nativeName: "لبنان",
    countryCode: "LB",
    isoNumeric: "422",
    flag: "🇱🇧",
    currency: "LBP",
    currencySymbol: "ل.ل",
    phoneCode: "+961",
    capitalCity: "Beirut",
  );
  static const lesotho = Country(
    name: "Lesotho",
    nativeName: "Lesotho",
    countryCode: "LS",
    isoNumeric: "426",
    flag: "🇱🇸",
    currency: "LSL",
    currencySymbol: "L",
    phoneCode: "+266",
    capitalCity: "Maseru",
  );
  static const liberia = Country(
    name: "Liberia",
    nativeName: "Liberia",
    countryCode: "LR",
    isoNumeric: "430",
    flag: "🇱🇷",
    currency: "LRD",
    currencySymbol: r"$",
    phoneCode: "+231",
    capitalCity: "Monrovia",
  );
  static const libya = Country(
    name: "Libya",
    nativeName: "ليبيا",
    countryCode: "LY",
    isoNumeric: "434",
    flag: "🇱🇾",
    currency: "LYD",
    currencySymbol: "ل.د",
    phoneCode: "+218",
    capitalCity: "Tripoli",
  );
  static const liechtenstein = Country(
    name: "Liechtenstein",
    nativeName: "Liechtenstein",
    countryCode: "LI",
    isoNumeric: "438",
    flag: "🇱🇮",
    currency: "CHF",
    currencySymbol: "Fr",
    phoneCode: "+423",
    capitalCity: "Vaduz",
  );
  static const lithuania = Country(
    name: "Lithuania",
    nativeName: "Lietuva",
    countryCode: "LT",
    isoNumeric: "440",
    flag: "🇱🇹",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+370",
    capitalCity: "Vilnius",
  );
  static const luxembourg = Country(
    name: "Luxembourg",
    nativeName: "Luxembourg",
    countryCode: "LU",
    isoNumeric: "442",
    flag: "🇱🇺",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+352",
    capitalCity: "Luxembourg City",
  );
  static const madagascar = Country(
    name: "Madagascar",
    nativeName: "Madagasikara",
    countryCode: "MG",
    isoNumeric: "450",
    flag: "🇲🇬",
    currency: "MGA",
    currencySymbol: "Ar",
    phoneCode: "+261",
    capitalCity: "Antananarivo",
  );
  static const malawi = Country(
    name: "Malawi",
    nativeName: "Malawi",
    countryCode: "MW",
    isoNumeric: "454",
    flag: "🇲🇼",
    currency: "MWK",
    currencySymbol: "MK",
    phoneCode: "+265",
    capitalCity: "Lilongwe",
  );
  static const malaysia = Country(
    name: "Malaysia",
    nativeName: "Malaysia",
    countryCode: "MY",
    isoNumeric: "458",
    flag: "🇲🇾",
    currency: "MYR",
    currencySymbol: "RM",
    phoneCode: "+60",
    capitalCity: "Kuala Lumpur",
  );
  static const maldives = Country(
    name: "Maldives",
    nativeName: "ދިވެހިރާއްޖެ",
    countryCode: "MV",
    isoNumeric: "462",
    flag: "🇲🇻",
    currency: "MVR",
    currencySymbol: ".ރ",
    phoneCode: "+960",
    capitalCity: "Malé",
  );
  static const mali = Country(
    name: "Mali",
    nativeName: "Mali",
    countryCode: "ML",
    isoNumeric: "466",
    flag: "🇲🇱",
    currency: "XOF",
    currencySymbol: "Fr",
    phoneCode: "+223",
    capitalCity: "Bamako",
  );
  static const malta = Country(
    name: "Malta",
    nativeName: "Malta",
    countryCode: "MT",
    isoNumeric: "470",
    flag: "🇲🇹",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+356",
    capitalCity: "Valletta",
  );
  static const marshallIslands = Country(
    name: "Marshall Islands",
    nativeName: "Marshall Islands",
    countryCode: "MH",
    isoNumeric: "584",
    flag: "🇲🇭",
    currency: "USD",
    currencySymbol: r"$",
    phoneCode: "+692",
    capitalCity: "Majuro",
  );
  static const mauritania = Country(
    name: "Mauritania",
    nativeName: "موريتانيا",
    countryCode: "MR",
    isoNumeric: "478",
    flag: "🇲🇷",
    currency: "MRU",
    currencySymbol: "UM",
    phoneCode: "+222",
    capitalCity: "Nouakchott",
  );
  static const mauritius = Country(
    name: "Mauritius",
    nativeName: "Maurice",
    countryCode: "MU",
    isoNumeric: "480",
    flag: "🇲🇺",
    currency: "MUR",
    currencySymbol: "₨",
    phoneCode: "+230",
    capitalCity: "Port Louis",
  );
  static const mexico = Country(
    name: "Mexico",
    nativeName: "México",
    countryCode: "MX",
    isoNumeric: "484",
    flag: "🇲🇽",
    currency: "MXN",
    currencySymbol: r"$",
    phoneCode: "+52",
    capitalCity: "Mexico City",
  );
  static const micronesia = Country(
    name: "Micronesia",
    nativeName: "Micronesia",
    countryCode: "FM",
    isoNumeric: "583",
    flag: "🇫🇲",
    currency: "USD",
    currencySymbol: r"$",
    phoneCode: "+691",
    capitalCity: "Palikir",
  );
  static const moldova = Country(
    name: "Moldova",
    nativeName: "Moldova",
    countryCode: "MD",
    isoNumeric: "498",
    flag: "🇲🇩",
    currency: "MDL",
    currencySymbol: "L",
    phoneCode: "+373",
    capitalCity: "Chisinau",
  );
  static const monaco = Country(
    name: "Monaco",
    nativeName: "Monaco",
    countryCode: "MC",
    isoNumeric: "492",
    flag: "🇲🇨",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+377",
    capitalCity: "Monaco",
  );
  static const mongolia = Country(
    name: "Mongolia",
    nativeName: "Монгол улс",
    countryCode: "MN",
    isoNumeric: "496",
    flag: "🇲🇳",
    currency: "MNT",
    currencySymbol: "₮",
    phoneCode: "+976",
    capitalCity: "Ulaanbaatar",
  );
  static const montenegro = Country(
    name: "Montenegro",
    nativeName: "Crna Gora",
    countryCode: "ME",
    isoNumeric: "499",
    flag: "🇲🇪",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+382",
    capitalCity: "Podgorica",
  );
  static const morocco = Country(
    name: "Morocco",
    nativeName: "المغرب",
    countryCode: "MA",
    isoNumeric: "504",
    flag: "🇲🇦",
    currency: "MAD",
    currencySymbol: "د.م.",
    phoneCode: "+212",
    capitalCity: "Rabat",
  );
  static const mozambique = Country(
    name: "Mozambique",
    nativeName: "Moçambique",
    countryCode: "MZ",
    isoNumeric: "508",
    flag: "🇲🇿",
    currency: "MZN",
    currencySymbol: "MT",
    phoneCode: "+258",
    capitalCity: "Maputo",
  );
  static const myanmar = Country(
    name: "Myanmar",
    nativeName: "မြန်မာ",
    countryCode: "MM",
    isoNumeric: "104",
    flag: "🇲🇲",
    currency: "MMK",
    currencySymbol: "Ks",
    phoneCode: "+95",
    capitalCity: "Naypyidaw",
  );
  static const namibia = Country(
    name: "Namibia",
    nativeName: "Namibia",
    countryCode: "NA",
    isoNumeric: "516",
    flag: "🇳🇦",
    currency: "NAD",
    currencySymbol: r"$",
    phoneCode: "+264",
    capitalCity: "Windhoek",
  );
  static const nauru = Country(
    name: "Nauru",
    nativeName: "Nauru",
    countryCode: "NR",
    isoNumeric: "520",
    flag: "🇳🇷",
    currency: "AUD",
    currencySymbol: r"$",
    phoneCode: "+674",
    capitalCity: "Yaren",
  );
  static const nepal = Country(
    name: "Nepal",
    nativeName: "नेपाल",
    countryCode: "NP",
    isoNumeric: "524",
    flag: "🇳🇵",
    currency: "NPR",
    currencySymbol: "₨",
    phoneCode: "+977",
    capitalCity: "Kathmandu",
  );
  static const netherlands = Country(
    name: "Netherlands",
    nativeName: "Nederland",
    countryCode: "NL",
    isoNumeric: "528",
    flag: "🇳🇱",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+31",
    capitalCity: "Amsterdam",
  );
  static const newZealand = Country(
    name: "New Zealand",
    nativeName: "Aotearoa",
    countryCode: "NZ",
    isoNumeric: "554",
    flag: "🇳🇿",
    currency: "NZD",
    currencySymbol: r"$",
    phoneCode: "+64",
    capitalCity: "Wellington",
  );
  static const nicaragua = Country(
    name: "Nicaragua",
    nativeName: "Nicaragua",
    countryCode: "NI",
    isoNumeric: "558",
    flag: "🇳🇮",
    currency: "NIO",
    currencySymbol: "C\$",
    phoneCode: "+505",
    capitalCity: "Managua",
  );
  static const niger = Country(
    name: "Niger",
    nativeName: "Niger",
    countryCode: "NE",
    isoNumeric: "562",
    flag: "🇳🇪",
    currency: "XOF",
    currencySymbol: "Fr",
    phoneCode: "+227",
    capitalCity: "Niamey",
  );
  static const nigeria = Country(
    name: "Nigeria",
    nativeName: "Nigeria",
    countryCode: "NG",
    isoNumeric: "566",
    flag: "🇳🇬",
    currency: "NGN",
    currencySymbol: "₦",
    phoneCode: "+234",
    capitalCity: "Abuja",
  );
  static const northKorea = Country(
    name: "North Korea",
    nativeName: "조선민주주의인민공화국",
    countryCode: "KP",
    isoNumeric: "408",
    flag: "🇰🇵",
    currency: "KPW",
    currencySymbol: "₩",
    phoneCode: "+850",
    capitalCity: "Pyongyang",
  );
  static const northMacedonia = Country(
    name: "North Macedonia",
    nativeName: "Северна Македонија",
    countryCode: "MK",
    isoNumeric: "807",
    flag: "🇲🇰",
    currency: "MKD",
    currencySymbol: "ден",
    phoneCode: "+389",
    capitalCity: "Skopje",
  );
  static const norway = Country(
    name: "Norway",
    nativeName: "Norge",
    countryCode: "NO",
    isoNumeric: "578",
    flag: "🇳🇴",
    currency: "NOK",
    currencySymbol: "kr",
    phoneCode: "+47",
    capitalCity: "Oslo",
  );
  static const oman = Country(
    name: "Oman",
    nativeName: "عمان",
    countryCode: "OM",
    isoNumeric: "512",
    flag: "🇴🇲",
    currency: "OMR",
    currencySymbol: "ر.ع.",
    phoneCode: "+968",
    capitalCity: "Muscat",
  );
  static const pakistan = Country(
    name: "Pakistan",
    nativeName: "پاکستان",
    countryCode: "PK",
    isoNumeric: "586",
    flag: "🇵🇰",
    currency: "PKR",
    currencySymbol: "₨",
    phoneCode: "+92",
    capitalCity: "Islamabad",
  );
  static const palau = Country(
    name: "Palau",
    nativeName: "Palau",
    countryCode: "PW",
    isoNumeric: "585",
    flag: "🇵🇼",
    currency: "USD",
    currencySymbol: r"$",
    phoneCode: "+680",
    capitalCity: "Ngerulmud",
  );
  static const palestine = Country(
    name: "Palestine",
    nativeName: "فلسطين",
    countryCode: "PS",
    isoNumeric: "275",
    flag: "🇵🇸",
    currency: "ILS",
    currencySymbol: "₪",
    phoneCode: "+970",
    capitalCity: "Ramallah",
  );
  static const panama = Country(
    name: "Panama",
    nativeName: "Panamá",
    countryCode: "PA",
    isoNumeric: "591",
    flag: "🇵🇦",
    currency: "PAB",
    currencySymbol: "B/.",
    phoneCode: "+507",
    capitalCity: "Panama City",
  );
  static const papuaNewGuinea = Country(
    name: "Papua New Guinea",
    nativeName: "Papua Niugini",
    countryCode: "PG",
    isoNumeric: "598",
    flag: "🇵🇬",
    currency: "PGK",
    currencySymbol: "K",
    phoneCode: "+675",
    capitalCity: "Port Moresby",
  );
  static const paraguay = Country(
    name: "Paraguay",
    nativeName: "Paraguay",
    countryCode: "PY",
    isoNumeric: "600",
    flag: "🇵🇾",
    currency: "PYG",
    currencySymbol: "₲",
    phoneCode: "+595",
    capitalCity: "Asunción",
  );
  static const peru = Country(
    name: "Peru",
    nativeName: "Perú",
    countryCode: "PE",
    isoNumeric: "604",
    flag: "🇵🇪",
    currency: "PEN",
    currencySymbol: "S/.",
    phoneCode: "+51",
    capitalCity: "Lima",
  );
  static const philippines = Country(
    name: "Philippines",
    nativeName: "Pilipinas",
    countryCode: "PH",
    isoNumeric: "608",
    flag: "🇵🇭",
    currency: "PHP",
    currencySymbol: "₱",
    phoneCode: "+63",
    capitalCity: "Manila",
  );
  static const poland = Country(
    name: "Poland",
    nativeName: "Polska",
    countryCode: "PL",
    isoNumeric: "616",
    flag: "🇵🇱",
    currency: "PLN",
    currencySymbol: "zł",
    phoneCode: "+48",
    capitalCity: "Warsaw",
  );
  static const portugal = Country(
    name: "Portugal",
    nativeName: "Portugal",
    countryCode: "PT",
    isoNumeric: "620",
    flag: "🇵🇹",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+351",
    capitalCity: "Lisbon",
  );
  static const qatar = Country(
    name: "Qatar",
    nativeName: "قطر",
    countryCode: "QA",
    isoNumeric: "634",
    flag: "🇶🇦",
    currency: "QAR",
    currencySymbol: "ر.ق",
    phoneCode: "+974",
    capitalCity: "Doha",
  );
  static const romania = Country(
    name: "Romania",
    nativeName: "România",
    countryCode: "RO",
    isoNumeric: "642",
    flag: "🇷🇴",
    currency: "RON",
    currencySymbol: "lei",
    phoneCode: "+40",
    capitalCity: "Bucharest",
  );
  static const russia = Country(
    name: "Russia",
    nativeName: "Россия",
    countryCode: "RU",
    isoNumeric: "643",
    flag: "🇷🇺",
    currency: "RUB",
    currencySymbol: "₽",
    phoneCode: "+7",
    capitalCity: "Moscow",
  );
  static const rwanda = Country(
    name: "Rwanda",
    nativeName: "Rwanda",
    countryCode: "RW",
    isoNumeric: "646",
    flag: "🇷🇼",
    currency: "RWF",
    currencySymbol: "Fr",
    phoneCode: "+250",
    capitalCity: "Kigali",
  );
  static const saintKittsAndNevis = Country(
    name: "Saint Kitts and Nevis",
    nativeName: "Saint Kitts and Nevis",
    countryCode: "KN",
    isoNumeric: "659",
    flag: "🇰🇳",
    currency: "XCD",
    currencySymbol: r"$",
    phoneCode: "+1-869",
    capitalCity: "Basseterre",
  );
  static const saintLucia = Country(
    name: "Saint Lucia",
    nativeName: "Saint Lucia",
    countryCode: "LC",
    isoNumeric: "662",
    flag: "🇱🇨",
    currency: "XCD",
    currencySymbol: r"$",
    phoneCode: "+1-758",
    capitalCity: "Castries",
  );
  static const saintVincentAndTheGrenadines = Country(
    name: "Saint Vincent and the Grenadines",
    nativeName: "Saint Vincent and the Grenadines",
    countryCode: "VC",
    isoNumeric: "670",
    flag: "🇻🇨",
    currency: "XCD",
    currencySymbol: r"$",
    phoneCode: "+1-784",
    capitalCity: "Kingstown",
  );
  static const samoa = Country(
    name: "Samoa",
    nativeName: "Samoa",
    countryCode: "WS",
    isoNumeric: "882",
    flag: "🇼🇸",
    currency: "WST",
    currencySymbol: "T",
    phoneCode: "+685",
    capitalCity: "Apia",
  );
  static const sanMarino = Country(
    name: "San Marino",
    nativeName: "San Marino",
    countryCode: "SM",
    isoNumeric: "674",
    flag: "🇸🇲",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+378",
    capitalCity: "City of San Marino",
  );
  static const saoTomeAndPrincipe = Country(
    name: "Sao Tome and Principe",
    nativeName: "São Tomé e Príncipe",
    countryCode: "ST",
    isoNumeric: "678",
    flag: "🇸🇹",
    currency: "STN",
    currencySymbol: "Db",
    phoneCode: "+239",
    capitalCity: "São Tomé",
  );
  static const saudiArabia = Country(
    name: "Saudi Arabia",
    nativeName: "المملكة العربية السعودية",
    countryCode: "SA",
    isoNumeric: "682",
    flag: "🇸🇦",
    currency: "SAR",
    currencySymbol: "ر.س",
    phoneCode: "+966",
    capitalCity: "Riyadh",
  );
  static const senegal = Country(
    name: "Senegal",
    nativeName: "Sénégal",
    countryCode: "SN",
    isoNumeric: "686",
    flag: "🇸🇳",
    currency: "XOF",
    currencySymbol: "Fr",
    phoneCode: "+221",
    capitalCity: "Dakar",
  );
  static const serbia = Country(
    name: "Serbia",
    nativeName: "Србија",
    countryCode: "RS",
    isoNumeric: "688",
    flag: "🇷🇸",
    currency: "RSD",
    currencySymbol: "дин.",
    phoneCode: "+381",
    capitalCity: "Belgrade",
  );
  static const seychelles = Country(
    name: "Seychelles",
    nativeName: "Seychelles",
    countryCode: "SC",
    isoNumeric: "690",
    flag: "🇸🇨",
    currency: "SCR",
    currencySymbol: "₨",
    phoneCode: "+248",
    capitalCity: "Victoria",
  );
  static const sierraLeone = Country(
    name: "Sierra Leone",
    nativeName: "Sierra Leone",
    countryCode: "SL",
    isoNumeric: "694",
    flag: "🇸🇱",
    currency: "SLE",
    currencySymbol: "Le",
    phoneCode: "+232",
    capitalCity: "Freetown",
  );
  static const singapore = Country(
    name: "Singapore",
    nativeName: "Singapore",
    countryCode: "SG",
    isoNumeric: "702",
    flag: "🇸🇬",
    currency: "SGD",
    currencySymbol: r"$",
    phoneCode: "+65",
    capitalCity: "Singapore",
  );
  static const slovakia = Country(
    name: "Slovakia",
    nativeName: "Slovensko",
    countryCode: "SK",
    isoNumeric: "703",
    flag: "🇸🇰",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+421",
    capitalCity: "Bratislava",
  );
  static const slovenia = Country(
    name: "Slovenia",
    nativeName: "Slovenija",
    countryCode: "SI",
    isoNumeric: "705",
    flag: "🇸🇮",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+386",
    capitalCity: "Ljubljana",
  );
  static const solomonIslands = Country(
    name: "Solomon Islands",
    nativeName: "Solomon Islands",
    countryCode: "SB",
    isoNumeric: "090",
    flag: "🇸🇧",
    currency: "SBD",
    currencySymbol: r"$",
    phoneCode: "+677",
    capitalCity: "Honiara",
  );
  static const somalia = Country(
    name: "Somalia",
    nativeName: "Soomaaliya",
    countryCode: "SO",
    isoNumeric: "706",
    flag: "🇸🇴",
    currency: "SOS",
    currencySymbol: "Sh",
    phoneCode: "+252",
    capitalCity: "Mogadishu",
  );
  static const southAfrica = Country(
    name: "South Africa",
    nativeName: "South Africa",
    countryCode: "ZA",
    isoNumeric: "710",
    flag: "🇿🇦",
    currency: "ZAR",
    currencySymbol: "R",
    phoneCode: "+27",
    capitalCity: "Pretoria",
  );
  static const southKorea = Country(
    name: "South Korea",
    nativeName: "대한민국",
    countryCode: "KR",
    isoNumeric: "410",
    flag: "🇰🇷",
    currency: "KRW",
    currencySymbol: "₩",
    phoneCode: "+82",
    capitalCity: "Seoul",
  );
  static const southSudan = Country(
    name: "South Sudan",
    nativeName: "South Sudan",
    countryCode: "SS",
    isoNumeric: "728",
    flag: "🇸🇸",
    currency: "SSP",
    currencySymbol: "£",
    phoneCode: "+211",
    capitalCity: "Juba",
  );
  static const spain = Country(
    name: "Spain",
    nativeName: "España",
    countryCode: "ES",
    isoNumeric: "724",
    flag: "🇪🇸",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+34",
    capitalCity: "Madrid",
  );
  static const sriLanka = Country(
    name: "Sri Lanka",
    nativeName: "ශ්‍රී ලංකාව",
    countryCode: "LK",
    isoNumeric: "144",
    flag: "🇱🇰",
    currency: "LKR",
    currencySymbol: "₨",
    phoneCode: "+94",
    capitalCity: "Colombo",
  );
  static const sudan = Country(
    name: "Sudan",
    nativeName: "السودان",
    countryCode: "SD",
    isoNumeric: "729",
    flag: "🇸🇩",
    currency: "SDG",
    currencySymbol: "ج.س.",
    phoneCode: "+249",
    capitalCity: "Khartoum",
  );
  static const suriname = Country(
    name: "Suriname",
    nativeName: "Suriname",
    countryCode: "SR",
    isoNumeric: "740",
    flag: "🇸🇷",
    currency: "SRD",
    currencySymbol: r"$",
    phoneCode: "+597",
    capitalCity: "Paramaribo",
  );
  static const sweden = Country(
    name: "Sweden",
    nativeName: "Sverige",
    countryCode: "SE",
    isoNumeric: "752",
    flag: "🇸🇪",
    currency: "SEK",
    currencySymbol: "kr",
    phoneCode: "+46",
    capitalCity: "Stockholm",
  );
  static const switzerland = Country(
    name: "Switzerland",
    nativeName: "Schweiz",
    countryCode: "CH",
    isoNumeric: "756",
    flag: "🇨🇭",
    currency: "CHF",
    currencySymbol: "Fr",
    phoneCode: "+41",
    capitalCity: "Bern",
  );
  static const syria = Country(
    name: "Syria",
    nativeName: "سوريا",
    countryCode: "SY",
    isoNumeric: "760",
    flag: "🇸🇾",
    currency: "SYP",
    currencySymbol: "£",
    phoneCode: "+963",
    capitalCity: "Damascus",
  );
  static const taiwan = Country(
    name: "Taiwan",
    nativeName: "臺灣",
    countryCode: "TW",
    isoNumeric: "158",
    flag: "🇹🇼",
    currency: "TWD",
    currencySymbol: r"$",
    phoneCode: "+886",
    capitalCity: "Taipei",
  );
  static const tajikistan = Country(
    name: "Tajikistan",
    nativeName: "Тоҷикистон",
    countryCode: "TJ",
    isoNumeric: "762",
    flag: "🇹🇯",
    currency: "TJS",
    currencySymbol: "смн",
    phoneCode: "+992",
    capitalCity: "Dushanbe",
  );
  static const tanzania = Country(
    name: "Tanzania",
    nativeName: "Tanzania",
    countryCode: "TZ",
    isoNumeric: "834",
    flag: "🇹🇿",
    currency: "TZS",
    currencySymbol: "Sh",
    phoneCode: "+255",
    capitalCity: "Dodoma",
  );
  static const thailand = Country(
    name: "Thailand",
    nativeName: "ประเทศไทย",
    countryCode: "TH",
    isoNumeric: "764",
    flag: "🇹🇭",
    currency: "THB",
    currencySymbol: "฿",
    phoneCode: "+66",
    capitalCity: "Bangkok",
  );
  static const timorLeste = Country(
    name: "Timor-Leste",
    nativeName: "Timor-Leste",
    countryCode: "TL",
    isoNumeric: "626",
    flag: "🇹🇱",
    currency: "USD",
    currencySymbol: r"$",
    phoneCode: "+670",
    capitalCity: "Dili",
  );
  static const togo = Country(
    name: "Togo",
    nativeName: "Togo",
    countryCode: "TG",
    isoNumeric: "768",
    flag: "🇹🇬",
    currency: "XOF",
    currencySymbol: "Fr",
    phoneCode: "+228",
    capitalCity: "Lomé",
  );
  static const tonga = Country(
    name: "Tonga",
    nativeName: "Tonga",
    countryCode: "TO",
    isoNumeric: "776",
    flag: "🇹🇴",
    currency: "TOP",
    currencySymbol: "T\$",
    phoneCode: "+676",
    capitalCity: "Nukuʻalofa",
  );
  static const trinidadAndTobago = Country(
    name: "Trinidad and Tobago",
    nativeName: "Trinidad and Tobago",
    countryCode: "TT",
    isoNumeric: "780",
    flag: "🇹🇹",
    currency: "TTD",
    currencySymbol: r"$",
    phoneCode: "+1-868",
    capitalCity: "Port of Spain",
  );
  static const tunisia = Country(
    name: "Tunisia",
    nativeName: "تونس",
    countryCode: "TN",
    isoNumeric: "788",
    flag: "🇹🇳",
    currency: "TND",
    currencySymbol: "د.ت",
    phoneCode: "+216",
    capitalCity: "Tunis",
  );
  static const turkey = Country(
    name: "Turkey",
    nativeName: "Türkiye",
    countryCode: "TR",
    isoNumeric: "792",
    flag: "🇹🇷",
    currency: "TRY",
    currencySymbol: "₺",
    phoneCode: "+90",
    capitalCity: "Ankara",
  );
  static const turkmenistan = Country(
    name: "Turkmenistan",
    nativeName: "Türkmenistan",
    countryCode: "TM",
    isoNumeric: "795",
    flag: "🇹🇲",
    currency: "TMT",
    currencySymbol: "m",
    phoneCode: "+993",
    capitalCity: "Ashgabat",
  );
  static const tuvalu = Country(
    name: "Tuvalu",
    nativeName: "Tuvalu",
    countryCode: "TV",
    isoNumeric: "798",
    flag: "🇹🇻",
    currency: "AUD",
    currencySymbol: r"$",
    phoneCode: "+688",
    capitalCity: "Funafuti",
  );
  static const uganda = Country(
    name: "Uganda",
    nativeName: "Uganda",
    countryCode: "UG",
    isoNumeric: "800",
    flag: "🇺🇬",
    currency: "UGX",
    currencySymbol: "Sh",
    phoneCode: "+256",
    capitalCity: "Kampala",
  );
  static const ukraine = Country(
    name: "Ukraine",
    nativeName: "Україна",
    countryCode: "UA",
    isoNumeric: "804",
    flag: "🇺🇦",
    currency: "UAH",
    currencySymbol: "₴",
    phoneCode: "+380",
    capitalCity: "Kyiv",
  );
  static const unitedArabEmirates = Country(
    name: "United Arab Emirates",
    nativeName: "الإمارات العربية المتحدة",
    countryCode: "AE",
    isoNumeric: "784",
    flag: "🇦🇪",
    currency: "AED",
    currencySymbol: "د.إ",
    phoneCode: "+971",
    capitalCity: "Abu Dhabi",
  );
  static const unitedKingdom = Country(
    name: "United Kingdom",
    nativeName: "United Kingdom",
    countryCode: "GB",
    isoNumeric: "826",
    flag: "🇬🇧",
    currency: "GBP",
    currencySymbol: "£",
    phoneCode: "+44",
    capitalCity: "London",
  );
  static const unitedStates = Country(
    name: "United States",
    nativeName: "United States",
    countryCode: "US",
    isoNumeric: "840",
    flag: "🇺🇸",
    currency: "USD",
    currencySymbol: r"$",
    phoneCode: "+1",
    capitalCity: "Washington, D.C.",
  );
  static const uruguay = Country(
    name: "Uruguay",
    nativeName: "Uruguay",
    countryCode: "UY",
    isoNumeric: "858",
    flag: "🇺🇾",
    currency: "UYU",
    currencySymbol: r"$",
    phoneCode: "+598",
    capitalCity: "Montevideo",
  );
  static const uzbekistan = Country(
    name: "Uzbekistan",
    nativeName: "O'zbekiston",
    countryCode: "UZ",
    isoNumeric: "860",
    flag: "🇺🇿",
    currency: "UZS",
    currencySymbol: "so'm",
    phoneCode: "+998",
    capitalCity: "Tashkent",
  );
  static const vanuatu = Country(
    name: "Vanuatu",
    nativeName: "Vanuatu",
    countryCode: "VU",
    isoNumeric: "548",
    flag: "🇻🇺",
    currency: "VUV",
    currencySymbol: "Vt",
    phoneCode: "+678",
    capitalCity: "Port Vila",
  );
  static const vaticanCity = Country(
    name: "Vatican City",
    nativeName: "Città del Vaticano",
    countryCode: "VA",
    isoNumeric: "336",
    flag: "🇻🇦",
    currency: "EUR",
    currencySymbol: "€",
    phoneCode: "+39",
    capitalCity: "Vatican City",
  );
  static const venezuela = Country(
    name: "Venezuela",
    nativeName: "Venezuela",
    countryCode: "VE",
    isoNumeric: "862",
    flag: "🇻🇪",
    currency: "VES",
    currencySymbol: "Bs.S",
    phoneCode: "+58",
    capitalCity: "Caracas",
  );
  static const vietnam = Country(
    name: "Vietnam",
    nativeName: "Việt Nam",
    countryCode: "VN",
    isoNumeric: "704",
    flag: "🇻🇳",
    currency: "VND",
    currencySymbol: "₫",
    phoneCode: "+84",
    capitalCity: "Hanoi",
  );
  static const yemen = Country(
    name: "Yemen",
    nativeName: "اليمن",
    countryCode: "YE",
    isoNumeric: "887",
    flag: "🇾🇪",
    currency: "YER",
    currencySymbol: "﷼",
    phoneCode: "+967",
    capitalCity: "Sana'a",
  );
  static const zambia = Country(
    name: "Zambia",
    nativeName: "Zambia",
    countryCode: "ZM",
    isoNumeric: "894",
    flag: "🇿🇲",
    currency: "ZMW",
    currencySymbol: "ZK",
    phoneCode: "+260",
    capitalCity: "Lusaka",
  );
  static const zimbabwe = Country(
    name: "Zimbabwe",
    nativeName: "Zimbabwe",
    countryCode: "ZW",
    isoNumeric: "716",
    flag: "🇿🇼",
    currency: "USD",
    currencySymbol: r"$",
    phoneCode: "+263",
    capitalCity: "Harare",
  );

  // --------------------------------------------------------------------------
  // The Complete List
  // --------------------------------------------------------------------------

  static const List<Country> all = [
    worldWide,
    afghanistan,
    albania,
    algeria,
    andorra,
    angola,
    antiguaAndBarbuda,
    argentina,
    armenia,
    australia,
    austria,
    azerbaijan,
    bahamas,
    bahrain,
    bangladesh,
    barbados,
    belarus,
    belgium,
    belize,
    benin,
    bhutan,
    bolivia,
    bosniaAndHerzegovina,
    botswana,
    brazil,
    brunei,
    bulgaria,
    burkinaFaso,
    burundi,
    cambodia,
    cameroon,
    canada,
    capeVerde,
    centralAfricanRepublic,
    chad,
    chile,
    china,
    colombia,
    comoros,
    congo,
    costaRica,
    croatia,
    cuba,
    cyprus,
    czechRepublic,
    denmark,
    djibouti,
    dominica,
    dominicanRepublic,
    ecuador,
    egypt,
    elSalvador,
    equatorialGuinea,
    eritrea,
    estonia,
    eswatini,
    ethiopia,
    fiji,
    finland,
    france,
    gabon,
    gambia,
    georgia,
    germany,
    ghana,
    greece,
    grenada,
    guatemala,
    guinea,
    guineaBissau,
    guyana,
    haiti,
    honduras,
    hungary,
    iceland,
    india,
    indonesia,
    iran,
    iraq,
    ireland,
    israel,
    italy,
    jamaica,
    japan,
    jordan,
    kazakhstan,
    kenya,
    kiribati,
    kuwait,
    kyrgyzstan,
    laos,
    latvia,
    lebanon,
    lesotho,
    liberia,
    libya,
    liechtenstein,
    lithuania,
    luxembourg,
    madagascar,
    malawi,
    malaysia,
    maldives,
    mali,
    malta,
    marshallIslands,
    mauritania,
    mauritius,
    mexico,
    micronesia,
    moldova,
    monaco,
    mongolia,
    montenegro,
    morocco,
    mozambique,
    myanmar,
    namibia,
    nauru,
    nepal,
    netherlands,
    newZealand,
    nicaragua,
    niger,
    nigeria,
    northKorea,
    northMacedonia,
    norway,
    oman,
    pakistan,
    palau,
    palestine,
    panama,
    papuaNewGuinea,
    paraguay,
    peru,
    philippines,
    poland,
    portugal,
    qatar,
    romania,
    russia,
    rwanda,
    saintKittsAndNevis,
    saintLucia,
    saintVincentAndTheGrenadines,
    samoa,
    sanMarino,
    saoTomeAndPrincipe,
    saudiArabia,
    senegal,
    serbia,
    seychelles,
    sierraLeone,
    singapore,
    slovakia,
    slovenia,
    solomonIslands,
    somalia,
    southAfrica,
    southKorea,
    southSudan,
    spain,
    sriLanka,
    sudan,
    suriname,
    sweden,
    switzerland,
    syria,
    taiwan,
    tajikistan,
    tanzania,
    thailand,
    timorLeste,
    togo,
    tonga,
    trinidadAndTobago,
    tunisia,
    turkey,
    turkmenistan,
    tuvalu,
    uganda,
    ukraine,
    unitedArabEmirates,
    unitedKingdom,
    unitedStates,
    uruguay,
    uzbekistan,
    vanuatu,
    vaticanCity,
    venezuela,
    vietnam,
    yemen,
    zambia,
    zimbabwe,
  ];
}
